### PR TITLE
handle projections mismatch between database and front end

### LINKED ISSUE #11: reproject geometries
Previously the postGIS database was unmarked EPSG 4326; currently it is in BC Albers. The front end expects measurements to be in degrees for easy display in leaflet, so a reprojection step will need to be added to queries.

### PR DESCRIPTION
**Pull request by corviday**
The new high-resolution postGIS database uses the BC Albers projection. The front end uses an unspecified latitude-longitude projection. This PR adds a couple of functions to convert between them.

**Rationale**: the postGIS database needed to have _some_ sort of projection for its various geographies, as we someday want to do calculations involving areas, such as determining how much a watershed and a salmon habitat overlap by so we can ignore incidental corner overlaps. As far as _which_ projection to pick, the input data is all in BC Albers, so that is the projection I used in the database. However, the data all needs to be translated to a latitude-longitude projection for the benefit of leaflet and the PCEX frontend, so _this_ backend needs to do that translation.

resolves #11

### CODE REVIEW

**Comment by corviday** [comment]
Demo: the[ production SCIP](https://services.pacificclimate.org/scip/app/), which was somewhat rushed into production.

**Review by QSparks — APPROVED** [review]
The BC Albers - EPSG: 4326 CRS conversion work looks good. Approved, with one small suggestion. The 2016 [rfc 7946](https://www.rfc-editor.org/rfc/rfc7946#section-4) standard for GeoJSON removes the alternative CRS field. Since we only use Albers-GeoJSON in testing, compliance isn't an issue, but we may want to remove it from [assume_4326](https://github.com/pacificclimate/scip-backend/blob/d2a2905e79689ea20b829b83bbc4de7c50925470/scip/api/projection.py#L23) to avoid potential issues.

**Comment by corviday** [comment]
@QSparks is there a more correct or up to date way to indicate what projection a geojson string is?

**Comment by QSparks** [comment]
> @QSparks is there a more correct or up to date way to indicate what projection a geojson string is?

No, the CRS for all GeoJSON data is fixed as EPSG:4326 and the ability to specify alternate CRSs has been deprecated. This should not pose an issue if we are confident that all relevant processing libraries can handle custom CRS definitions in the GeoJson.

**Comment by corviday** [comment]
Huh, weird. That's very useful to know, thanks.

**Pull request merged**
